#!/bin/sh

PLAYER="spotify"
FORMAT="{{title}}"
PLAYERCTL_STATUS=$(playerctl --player=$PLAYER status 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
	STATUS=$PLAYERCTL_STATUS 
       	DATA=$(playerctl --player=$PLAYER metadata --format "$FORMAT") 

else
	STATUS="No player is running"
	DATA=""
fi

echo "|🪗 $STATUS 🎻 $DATA 🎺"
