#!/bin/bash

zscroll -b "| " -a " |" -u true "sb-music"

# see man zscroll for documentation of the following parameters
#zscroll -l 30 \
#        --delay 1 \
#        --scroll-padding "  " \
#        --match-command "sb-music" \
#        --match-text "Playing" "--scroll 1" \
#        --match-text "Paused" "--scroll 0" \
#	--update-check true "sb-music" &
